name: dart_sql
description: A declarative front end for SQL libries like moor:ffi that enables
  you to construct SQL queries using Dart syntax.
version: 0.0.11+7
homepage: https://aeyrium.com

environment:
  sdk: ">=3.4.0"

dev_dependencies:
  test: ^1.19.2
